### ISSUE TITLE
Min/max values missing from integer range validator context

### ISSUE THREAD

**Issue by Skielex** [Breeze/breeze.js#83] opened 2015-03-23 15:20 UTC
The function `intRangeValidatorCtor(validatorName, minValue, maxValue, context)` is responsible for creating the range validators and set their message templates and context. However, it appears that their `minValue` and `maxValue` are never set on the `context`. This means they're not accessible for later use (we the context values for localization).

One solution is to add the following piece of code to the `intRangeValidatorCtor`:
```javascript
    if (!context) {
      context = {};
    }
    context.maxValue = maxValue;
    context.minValue = minValue;
```
This way we ensure that the `minValue` and `maxValue` are available in the `context` as I assume they should be.

**Comment by wardbell** [comment] 2015-04-02 21:34
That *seems* like a useful extension. But is it *actually* useful?

As you probably know, you can define the message for any validator that you define by hand. The problem from your perspective probably arises w/r/t the default versions of the various integer range validators that are created based on server-supplied metadata. These message templates are defined in English and have the min and max values baked in.

If you want to localize the messages for default validators, you have to iterate through the `breeze.Validator.ctor.messageTemplates` and localize them *before loading metadata*. You could set these messages (including min and max values) exactly as you wish.

Upon reflection I can see why even this would be easier if the min/max were in the `context` and that is certainly true should you choose to set the `context.message` property with a function that calculates the message on the fly.

Accordingly, I'm inclined to implement the function prelude like this:

    context = context || {};
    if (minValue !== undefined) { context.min = minValue; }
    if (maxValue !== undefined) { context.max = maxValue; }
    var templateExists = context.messageTemplate || ctor.messageTemplates[validatorName];

You MUST understand that the `context.max` and `context.min` are **read-only** values. Changing the `context.min` later will NOT change the actual value used in the validator's calculation, even if the message itself reports otherwise.

This limitation is **by design**. Validators are supposed to be immutable after instantiation.

Perhaps it goes w/o saying that this approach would override values for `context.min` and `context.max`. For example, after:

    var aRangeValidator = intRangeValidatorCtor(0,10, {min: 1, max: 11}); // WAT?

The `context.min === 0` and  the `context.max === 10`. I think that's a reasonable outcome.

Committed the change. Should show up in next release.

**Closed by wardbell** 2015-04-02 21:34 UTC
